### ISSUE TITLE
Added Partition of Array algorithm

### ISSUE THREAD

**Issue by MilanshuRathi** [TechOUs/DSKaKhel#63]
## Name the program which is added

Partition of array

## Programming Language 

C++

## I AM

a student 

## GITHUB USERNAME

MilanshuRathi

**Comment by GauravWalia19** [comment]
Thanks for choosing our repository for contributing to Hacktober Fest 20
As a part of the new process this Issue is marked as hacktoberfest-expiry & closed
Please check our new updated contribution guidelines [here](https://github.com/TechOUs/DSKaKhel/blob/master/CONTRIBUTING.md)
