### ISSUE TITLE
HacktoberFest20

### ISSUE THREAD

**Issue by riyavaryani** [TechOUs/DSKaKhel#70]
## Name the program which you are adding

Josephus Problem for recursion

## Programming Language you will code

C++

## YOU ARE

a student 

## GITHUB USERNAME

riyavaryani

**Comment by GauravWalia19** [comment]
Thanks for choosing our repository for contributing to Hacktober Fest 20
As a part of the new process this Issue is marked as hacktoberfest-expiry & closed
Please check our new updated contribution guidelines [here](https://github.com/TechOUs/DSKaKhel/blob/master/CONTRIBUTING.md)
