### ISSUE TITLE
HacktoberFest20

### ISSUE THREAD

**Issue by nasareen** [TechOUs/DSKaKhel#71]
#66 More methods added to Java String Class

**Comment by GauravWalia19** [comment]
Please comment **list the methods here** which you want to add.

**Comment by GauravWalia19** [comment]
Thanks for choosing our repository for contributing to Hacktober Fest 20
As a part of the new process this Issue is marked as hacktoberfest-expiry & closed
Please check our new updated contribution guidelines [here](https://github.com/TechOUs/DSKaKhel/blob/master/CONTRIBUTING.md)
