### ISSUE TITLE
HacktoberFest20

### ISSUE THREAD

**Issue by nitch193** [TechOUs/DSKaKhel#81]
## Name the program which you are adding

Number of trailing zeros in the factorial of a number.

## Programming Language you will code

C++

## YOU ARE

a student

## GITHUB USERNAME

nitch193

**Comment by GauravWalia19** [comment]
Please send us Pull Request with the changes. Don't forget to update the README.

**Comment by GauravWalia19** [comment]
Thanks for choosing our repository for contributing to Hacktober Fest 20
As a part of the new process this Issue is marked as hacktoberfest-expiry & closed
Please check our new updated contribution guidelines [here](https://github.com/TechOUs/DSKaKhel/blob/master/CONTRIBUTING.md)
