### ISSUE TITLE
HacktoberFest20

### ISSUE THREAD

**Issue by nitch193** [TechOUs/DSKaKhel#82]
## Name the program which you are adding

Deletion of element in array.

## Programming Language you will code

C

## YOU ARE

a student 

## GITHUB USERNAME

nitch193

**Comment by Catastrophic866** [comment]
[https://github.com/TechOUs/Data-Structures/pull/83#issue-505273602](url)
please merge the above repo

**Comment by GauravWalia19** [comment]
@nitch193 please send us Pull Request with the changes

**Comment by nitch193** [comment]
ok i will send it soon

**Comment by GauravWalia19** [comment]
Thanks for choosing our repository for contributing to Hacktober Fest 20
As a part of the new process this Issue is marked as hacktoberfest-expiry & closed
Please check our new updated contribution guidelines [here](https://github.com/TechOUs/DSKaKhel/blob/master/CONTRIBUTING.md)
