### ISSUE TITLE
HacktoberFest20

### ISSUE THREAD

**Issue by Anonymous866** [TechOUs/DSKaKhel#85]
## Name the program which you are adding

Add two numbers represented by linked lists

## Programming Language you will code

JAVA

## YOU ARE

a student

## GITHUB USERNAME

Catastrophic866

Link of my PR - [https://github.com/TechOUs/Data-Structures/pull/84#issue-505274092](url)

**Comment by Catastrophic866** [comment]
Please check i have done all the required things
[https://github.com/TechOUs/Data-Structures/pull/87#issue-505299041](url)

My PRs - 
[https://github.com/TechOUs/Data-Structures/pull/83#issue-505273602](url)
[https://github.com/TechOUs/Data-Structures/pull/84#issue-505274092](url)
[https://github.com/TechOUs/Data-Structures/pull/86#issue-505298632](url)

**Comment by GauravWalia19** [comment]
Thanks for choosing our repository for contributing to Hacktober Fest 20
As a part of the new process this Issue is marked as hacktoberfest-expiry & closed
Please check our new updated contribution guidelines [here](https://github.com/TechOUs/DSKaKhel/blob/master/CONTRIBUTING.md)
